# cluster_config.yml - cluster configuration
## NOTE: if slurm log folder doesn't exist, job will FAIL
## the folders below must (currently) be manually created
## bc they need to be used before snakemake would make them
__default__:
    partition: bmm
    time: 02:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 1 
    mem: 1GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/slurm-%j.stderr"
    stdout: "logs/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
ftp_get_fq:
    partition: bmm
    time: 2:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 9
    mem: 2GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/get_data/slurm-%j.stderr"
    stdout: "logs/get_data/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
adapter_trim:
    partition: bmm
    time: 2:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 10
    mem: 5GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/trimmomatic/slurm-%j.stderr"
    stdout: "logs/trimmomatic/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
kmer_trim:
    partition: bmm
    time: 2:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 1
    mem: 30GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/khmer/slurm-%j.stderr"
    stdout: "logs/khmer/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
polyA_trim:
    partition: bmm
    time: 2:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 10
    mem: 5GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/cutadapt/slurm-%j.stderr"
    stdout: "logs/cutadapt/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
split_pairs:
    partition: bmm
    time: 2:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 3
    mem: 2GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/khmer/slurm-%j.stderr"
    stdout: "logs/khmer/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
trinity:
    partition: bmm
    time: 3-00:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 20
    mem: 100GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/trinity/slurm-%j.stderr"
    stdout: "logs/trinity/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
transdecoder_longorfs:
    partition: bmm
    time: 08:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 10
    mem: 5GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/transdecoder/slurm-%j.stderr"
    stdout: "logs/transdecoder/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
transdecoder_predict:
    partition: bmm
    time: 8:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 10
    mem: 5GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/transdecoder/slurm-%j.stderr"
    stdout: "logs/transdecoder/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
pear_read_merging:
    partition: bmm
    time: 8:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 10
    mem: 5GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/pear/slurm-%j.stderr"
    stdout: "logs/pear/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
plass:
    partition: bmm
    time: 6:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 4
    mem: 20GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/plass/slurm-%j.stderr"
    stdout: "logs/plass/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
cluster_plass:
    partition: bmm
    time: 1-00:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 10
    mem: 20GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/plass/slurm-%j.stderr"
    stdout: "logs/plass/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
spacegraphcats_build:
    partition: bmm
    time: 2-00:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 1
    mem: 70GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/spacegraphcats/slurm-%j.stderr"
    stdout: "logs/spacegraphcats/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
spacegraphcats_extract_reads_contigs:
    partition: bmm
    time: 2-00:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 1
    mem: 70GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/spacegraphcats/slurm-%j.stderr"
    stdout: "logs/spacegraphcats/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
plass_remove_stop:
    partition: bmm
    time: 2:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 1
    mem: 1GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/plass/slurm-%j.stderr"
    stdout: "logs/plass/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
plass_eliminate_identical_contigs:
    partition: bmm
    time: 04:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 1
    mem: 5GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/cdhit/slurm-%j.stderr"
    stdout: "logs/cdhit/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
cluster_plass:
    partition: bmm
    time: 04:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 4
    mem: 4GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/cdhit/slurm-%j.stderr"
    stdout: "logs/cdhit/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
makeblastdb_plass_assembly:
    partition: bmm
    time: 01:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 1
    mem: 2GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/blast/slurm-%j.stderr"
    stdout: "logs/blast/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
assemble_nbhd:
    partition: bmm
    time: 6:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 20
    mem: 80GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/plass/slurm-%j.stderr"
    stdout: "logs/plass/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
paladin_map_sgc_contigs_x_plass:
    partition: bmm
    time: 1:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 20
    mem: 10GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/paladin/slurm-%j.stderr"
    stdout: "logs/paladin/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
extract_coding:
    partition: bmm
    time: 3-00:00:00 # time limit for each job
    nodes: 1
    cpus_per_task: 1
    mem: 10GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/khtools/slurm-%j.stderr"
    stdout: "logs/khtools/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
plass_sourmash_compute:
    partition: bmm
    time: 6:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 1GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/sourmash/slurm-%j.stderr"
    stdout: "logs/sourmash/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
plass_sourmash_compare_cosine:
    partition: bmm
    time: 6:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 1GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/sourmash/slurm-%j.stderr"
    stdout: "logs/sourmash/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
plass_sourmash_compare_jaccard:
    partition: bmm
    time: 6:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 1GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/sourmash/slurm-%j.stderr"
    stdout: "logs/sourmash/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
plass_sourmash_compare_cosine:
    partition: bmm
    time: 6:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 1GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/sourmash/slurm-%j.stderr"
    stdout: "logs/sourmash/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
plass_sourmash_plot_jaccard:
    partition: bmm
    time: 6:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 1GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/sourmash/slurm-%j.stderr"
    stdout: "logs/sourmash/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
paladin_quant:
    partition: bmm
    time: 3:00:00 
    nodes: 1
    cpus_per_task: 10
    mem: 10GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/salmon/slurm-%j.stderr"
    stdout: "logs/salmon/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
mmseqs_map:
    partition: bmm
    time: 6:00:00 
    nodes: 1
    cpus_per_task: 10
    mem: 10GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/mmseqs/slurm-%j.stderr"
    stdout: "logs/mmseqs/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
mmseqs_results_to_sam:
    partition: bmm
    time: 6:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 10GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/mmseqs/slurm-%j.stderr"
    stdout: "logs/mmseqs/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
createdb_MERCref:
    partition: bmm
    time: 6:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 10GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/mmseqs/slurm-%j.stderr"
    stdout: "logs/mmseqs/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
metaeuk_easypredict_plass:
    partition: bmm
    time: 10:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 20GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/metaeuk/slurm-%j.stderr"
    stdout: "logs/metaeuk/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
metaeuk_easypredict_trinity: 
    partition: bmm
    time: 10:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 20GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/metaeuk/slurm-%j.stderr"
    stdout: "logs/metaeuk/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
khtools_comparekmers:
    partition: bmm
    time: 10-00:00:00 
    nodes: 1
    cpus_per_task: 20
    mem: 30GB
    chdir: /home/ntpierce/2020-pep/kcompare_out
    stderr: "logs/khtools/slurm-%j.stderr"
    stdout: "logs/khtools/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
busco_trans:
    partition: bmm
    time: 1-00:00:00 
    nodes: 1
    cpus_per_task: 10
    mem: 20GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/busco/slurm-%j.stderr"
    stdout: "logs/busco/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
busco_plass:
    partition: bmm
    time: 1-00:00:00 
    nodes: 1
    cpus_per_task: 10
    mem: 20GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/busco/slurm-%j.stderr"
    stdout: "logs/busco/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
busco_jpep:
    partition: bmm
    time: 1-00:00:00 
    nodes: 1
    cpus_per_task: 10
    mem: 20GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/busco/slurm-%j.stderr"
    stdout: "logs/busco/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
sonicparanoid:
    partition: bmm
    time: 10-00:00:00 
    nodes: 1
    cpus_per_task: 20
    mem: 50GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/sonicparanoid/slurm-%j.stderr"
    stdout: "logs/sonicparanoid/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
diamond_makedb_nr:
    partition: bmm
    time: 1-00:00:00 
    nodes: 1
    cpus_per_task: 1
    mem: 10GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/diamond/slurm-%j.stderr"
    stdout: "logs/diamond/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"
diamond_blastp_extract_coding:
    partition: bmm
    time: 8:00:00 
    nodes: 1
    cpus_per_task: 10
    mem: 5GB
    chdir: /home/ntpierce/2020-pep/orthopep_out
    stderr: "logs/diamond/slurm-%j.stderr"
    stdout: "logs/diamond/slurm-%j.stdout"
    jobname: "{rule}.w{wildcards}"

